name: Build Projects

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: cd packages/shared && npm run build
    - run: ls 
    - run: cd packages/admin/ && npm run build
    - run: cd packages/client/ && npm run build
    - run: cd packages/server/ && npm run build
